# Generated by Django 4.2.8 on 2023-12-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycomments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='improvedcomment',
            options={'ordering': ['-submit_date']},
        ),
    ]
