# Generated by Django 4.2.8 on 2023-12-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycomments', '0002_alter_improvedcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='improvedcomment',
            options={'ordering': ['-submit_date'], 'permissions': [('can_moderate', 'Can moderate comments')], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
